---
- hosts:
  - server
  vars_files:
  - variables.yml
  tasks:
  - name: "apt requirements"
    become: yes
    apt:
      name:
      - nginx
      state: latest
  - name: "ssl certificate"
    become: yes
    template:
      src: templates/nanvel_name_chain.crt
      dest: "/etc/ssl/{{ project_name }}_chain.crt"
    notify: nginx restart
  - name: "ssl key"
    become: yes
    template:
      src: templates/nanvel_name.key
      dest: "/etc/ssl/{{ project_name }}.key"
    notify: nginx restart
  - name: "nginx configuration"
    become: yes
    template:
      src: templates/nginx.j2
      dest: "/etc/nginx/sites-enabled/{{ project_name }}"
    notify: nginx restart
  handlers:
  - name: nginx restart
    service:
      name: nginx
      state: restarted
